import = [
    "~/.config/alacritty/themes/themes/hardhacker.toml"
]

[font]
size=20

# Use the exact family shown by fc-list, e.g.:
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }
